import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Syne, Space_Grotesk } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const space = Space_Grotesk({
  subsets: ["latin"],
 weight: ["400", "500", "600", "700"],
});

const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});


export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
export { syne, space };

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
